# Generated by Django 4.2.11 on 2024-12-17 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('email', models.EmailField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pc_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('img1', models.ImageField(null=True, upload_to='images')),
                ('img2', models.ImageField(null=True, upload_to='images')),
                ('img3', models.ImageField(null=True, upload_to='images')),
                ('img4', models.ImageField(null=True, upload_to='images')),
                ('RAM', models.CharField(max_length=20)),
                ('Processor', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=5000)),
                ('Price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_name', models.CharField(default='you dont have history yet', max_length=500)),
                ('Deposit_amount', models.IntegerField(default=0)),
                ('Enter_email', models.EmailField(default='Empty', max_length=254)),
                ('screen', models.ImageField(default='you dont have history yet', upload_to='images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=2000000)),
                ('mesg', models.CharField(default='thanks for being here.', max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
