# Generated by Django 4.2.11 on 2024-12-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0003_wallet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
