# Generated by Django 4.2.11 on 2024-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0004_wallet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='screen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
