# Generated by Django 4.2.11 on 2024-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0007_rename_screen_wallet_upload_transaction_screenshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Upload_transaction_screenshot',
            new_name='Upload_transaction_receipt_screenshot',
        ),
        migrations.RemoveField(
            model_name='pc_store',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='pc_store',
            name='img3',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
